password_policy:
  min_length: 10
  require_uppercase: true
  require_lowercase: true
  require_digit: true
  require_special: true
  min_categories: 3
  max_failed_attempts: 3

auth_questions:
  - "What is your favorite food?"
  - "What is your mother's name?"

database:
  host: "127.0.0.1"
  user: "myuser"
  database: "user_data"

email_settings:
  smtp_host: smtp.gmail.com
  smtp_port: 587 # 465 for SSL
  sender_email: neomibashari1899@gmail.com
  reset_password_url_template: "http://localhost:5173/reset-password?token={token}" 